# Generated by Django 4.0.6 on 2022-10-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emo',
            name='EU',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='emo',
            name='emotion',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='emo',
            name='source',
            field=models.IntegerField(blank=True),
        ),
    ]
