# Generated by Django 4.0.6 on 2022-11-14 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_emo_eu_alter_emo_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='emo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
