# Generated by Django 4.0.6 on 2022-11-14 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_emo_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emo',
            name='date_time',
        ),
        migrations.AddField(
            model_name='emo',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emo',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
